# Generated by Django 5.1.2 on 2025-05-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('intro_paragraphs', models.JSONField()),
                ('responsibilities', models.JSONField()),
                ('requirements', models.JSONField()),
                ('benefits', models.JSONField()),
                ('apply_link', models.CharField(max_length=255)),
                ('all_jobs_link', models.CharField(max_length=255)),
            ],
        ),
    ]
